/* Research positions are a reading itinerary, not a hierarchy of truth.
 * Scientific status and a visitor's discoveries are deliberately independent. */
window.ZUIZUI_TOWER = {
  version: '2026-09-06-tower-1',
  checkedAt: '2026-09-06',
  floors: [
    { id:'field', roman:'I', glyph:'⌁', name:'現地', subtitle:'世界は、記録の外にもある。', color:'#97b4a3' },
    { id:'record', roman:'II', glyph:'◎', name:'記録', subtitle:'残ったものと、残らなかったもの。', color:'#97baca' },
    { id:'worlds', roman:'III', glyph:'⌖', name:'可能性', subtitle:'同じ記録に、違う世界が重なる。', color:'#b0b9d0' },
    { id:'state', roman:'IV', glyph:'◇', name:'区別', subtitle:'何を忘れてよいのか。', color:'#c4b2c8' },
    { id:'future', roman:'V', glyph:'⋈', name:'未来', subtitle:'違う道から、同じ状態へ？', color:'#d6bc9d' }
  ],
  // One doorway per scientific repository. Roles can cross several floors.
  repos: [
    ['hotarubukuro',0,'花色の地理','ホタルブクロの花色と地理的変異。','observable,record'],
    ['fcp',0,'花色と空間','花色の地理的構造を比較する。','observable,identified'],
    ['chun',0,'花色と時間','進化時間・分子情報から花色の反復を考える。','observable,identified'],
    ['azami',0,'アザミの現在','画像形質と環境の現在の構造。','observable,record'],
    ['EAzami',0,'アザミの履歴','反復と歴史的深さを区別する。','observable,identified,possible'],
    ['aza3',0,'アザミの現地','祖先・表現型・細胞型を一次データで照合する。','action,observable,record'],
    ['island',0,'島の比較','花・繁殖形質の変化が、いつ・どこで生じるか。','observable,identified'],
    ['izu-core',0,'島の相互作用','島の相互作用と応答を条件付きで比較する。','observable,represented,identified'],
    ['shimahotarubukuro',0,'島の花','伊豆諸島のシマホタルブクロの表現型。','observable,record'],
    ['pollipi',1,'記録する装置','訪花を物理的な観測・記録へ変換する。','observable,record,action'],
    ['insepi',1,'観測者を調べる','装置の失敗を、介入と独立な真値で切り分ける。','observable,record,action'],
    ['rec',1,'入らなかった記録','存在しても利用可能な行にならない支持域を扱う。','possible,observable,record'],
    ['v3',1,'残った参照情報','保持された側情報で、両立する世界を絞る。','observable,record,represented'],
    ['tnoa',1,'記録の意味','保持された観測の区別を、早すぎる統合から守る。','record,represented'],
    ['boundary',2,'見分ける境界','現在の観測写像が区別できない説明を明示する。','represented,identified'],
    ['mrod',2,'次の観測','残る機構の曖昧さを分ける、次の測定を選ぶ。','identified,action'],
    ['sdmr',2,'環境の座標','ニッチ推定に採用する環境座標を吟味する。','record,represented,identified'],
    ['odsp',2,'多次元のニッチ','失われたニッチ軸と状態別の予測を扱う。','record,represented,possible'],
    ['eog',2,'両立する世界','可能性・到達性・観測を分け、世界集合を更新する。','record,identified,possible'],
    ['284b',2,'答え同士の照合','異なる推定対象の答えを、共通の生物学的関係空間で照合する。','represented,identified,relation-check'],
    ['acsp',2,'現地への出口','占有を断言せず、限られた調査候補パッチを返す。','identified,action'],
    ['ccoc',3,'未来の区別','将来の接続や操作で、現在の同一視が壊れる。','possible'],
    ['mltr',3,'履歴の区別','置換や履歴の違いで、受け継いだ意味が壊れる。','possible'],
    ['mrm',3,'機構の区別','同じ見かけでも、保持する機構が応答を変える。','possible,identified'],
    ['crest',3,'必要な状態','契約に対し、安全に忘れられる最小限の状態を考える。','possible,represented,identified'],
    ['ced',3,'言えること','必要な区別を証拠が支え、対象を報告できるか。','identified,reportable,action'],
    ['theouni',3,'理論の文法','理論の採用条件とポートフォリオを横断する。','possible,reportable'],
    ['sch',4,'共有する形','一つの形質座標を共有する機能の葛藤。','possible,observable'],
    ['balance',4,'留まる形','分化の費用を払わず、葛藤を保つ条件。','possible,observable'],
    ['bita',4,'分かれる形','次元の分化で回復する利得と、機構の同定限界。','possible,observable,identified'],
    ['payoff',4,'形の進化','構造の利得を、侵入・共存・集団動態へ運ぶ。','possible'],
    ['eco-genetic-criticality',4,'相互作用の状態','有限な生態・遺伝モデルの状態分離。','possible'],
    ['eco-genetic-warning-extensions',4,'未来に効く関係','関係状態と警告の妥当性を吟味する。','possible,represented,identified'],
    ['egwee',4,'自然からの照合','残差を解釈する前に、自然データで状態の十分さを問う。','observable,represented,identified,reportable']
  ],
  aliases: {'eco-genetic-criticality':'EGC','eco-genetic-warning-extensions':'EGWE','shimahotarubukuro':'島ホタルブクロ'},
  motifs: [
    {id:'return', floor:0, angle:0.05, glyph:'⌁', title:'現地に戻る', route:'ACSP ⇢ aza3 / 島 / 花', status:'open',
     text:'候補パッチは、存在や検出の保証ではない。新しい現地観測が、モデルへ戻ってくる。',
     receipt:'同じ努力量・検出可能性の条件で、候補地と対照地を前向きに調査する。',
     source:'acsp', path:'README.md', sourceBlob:'a56e8dd63958ec2a2354a6e7b0ed195d1582e83f',
     repos:['acsp','aza3','island','pollipi'], contacts:['field-return','same-system']},
    {id:'record', floor:1, angle:1.38, glyph:'◎', title:'同じ影、違う世界', route:'REC · V3 · TNOA → Boundary → MROD', status:'established',
     text:'三つの情報操作は兄弟。観測が残した曖昧さを、次の測定で分ける。',
     receipt:'この読解上の接点と、実装済みの単一システム接続は別。物理装置との前向きな閉合は残る。',
     source:'mrod', path:'README.md', sourceBlob:'51a3ba48746b0d772da3e8d11dc41af2d5f2fbbb',
     repos:['rec','v3','tnoa','boundary','mrod','pollipi','insepi'], contacts:['observation-map','next-observation','same-system']},
    {id:'answer', floor:2, angle:2.55, glyph:'⌖', title:'答えは、同じ尺度でなくていい', route:'SDMR / ODSP / EOG ↔ 284b · ACSP', status:'bounded',
     text:'座標・多次元状態・両立世界は異なる仕事。284bは別々の答えを関係空間で照合し、ACSPは調査先を返す。',
     receipt:'284bは空のstagingではない。凍結した関係空間・外部生物学的制約が必要。全系列の直結APIや普遍的実証は未確認。',
     source:'284b', path:'docs/product_b_eog_sdmr_relation_space_alignment.md', sourceBlob:'a5ca53b09aed0adaaebeff24602a58d833f7ac94',
     repos:['sdmr','odsp','eog','284b','acsp'], contacts:['niche-worlds','relation-space','eog-mrod','field-return']},
    {id:'state', floor:3, angle:3.80, glyph:'◇', title:'必要な区別と、見える区別', route:'CCOC · MLTR · MRM → CREST → CED ← Boundary', status:'established',
     text:'状態に必要な区別と、観測で識別できる区別は同じではない。CEDが、証拠から言える対象を問う。',
     receipt:'MRM→MROD、CED↔MRODには、候補観測・応答・費用を揃えた明示的な変換が必要。',
     source:'crest', path:'README.md', sourceBlob:'16c8dfba6f6351a79cd61ebe4976539425df4788',
     repos:['ccoc','mltr','mrm','crest','ced','boundary','mrod'], contacts:['state-obligation','evidence-license','mrm-mrod','ced-mrod','natural-state']},
    {id:'future', floor:4, angle:5.16, glyph:'⋈', title:'違う出発点、同じ未来？', route:'SCH · BALANCE · BITA → PAYOFF ⇠ EGWE → EGWEE', status:'proposed',
     text:'構造の利得と関係状態をつなぐ候補。島と都市は、異なる履歴から同じ未来関連状態へ至るかを試す場。',
     receipt:'向きに注意：現在の提案は EGWE状態→PAYOFF文脈。逆向きには、同一系で構造→関係状態→未来機能を測る。EGWEEは遺伝的警告の検証ではない。',
     source:'egwee', path:'README.md', sourceBlob:'1199292fe1d6984c6fbbd4928729f6edf880d688',
     repos:['sch','balance','bita','payoff','eco-genetic-criticality','eco-genetic-warning-extensions','egwee','island','izu-core'],
     contacts:['architecture-game','warning-projection','state-payoff','architecture-state','island-urban']}
  ],
  contacts: [
    {id:'observation-map', from:['rec','v3','tnoa'], to:['boundary'], type:'information-operations', status:'established', condition:'支持域・参照情報・意味の保存が、観測写像の区別を決める。'},
    {id:'next-observation', from:['boundary'], to:['mrod'], type:'design-response', status:'established', condition:'残る両立集合と、候補観測が作る検証済みの結果分割を渡す。'},
    {id:'state-obligation', from:['ccoc','mltr','mrm'], to:['crest'], type:'required-state', status:'established', condition:'未来・履歴・機構の三つの責任。直列の手法ではない。'},
    {id:'evidence-license', from:['crest','boundary'], to:['ced'], type:'evidence-licensing', status:'established', condition:'必要な状態、観測の識別集合、報告対象を同じ契約に置く。'},
    {id:'niche-worlds', from:['sdmr','odsp'], to:['eog'], type:'conceptual-corridor', status:'bounded', condition:'環境座標→多次元状態→両立・到達世界。開発系譜と概念関係を区別し、直結APIを断言しない。'},
    {id:'relation-space', from:['sdmr','eog'], to:['284b'], type:'cross-estimand-check', status:'bounded', condition:'別の推定器・推定対象を許し、共通の場所×生物学的機会へ写して外部関係を照合する。'},
    {id:'field-return', from:['eog','acsp'], to:['aza3','island'], type:'prospective-field-return', status:'open', condition:'候補パッチと対照地を、新しい現地データ・努力量・検出可能性で比較する。候補パッチ≠占有≠検出保証。'},
    {id:'architecture-game', from:['sch','balance','bita'], to:['payoff'], type:'abstraction', status:'established', condition:'葛藤負荷・回復量・構造費用を、継承される構造の利得として運ぶ。'},
    {id:'warning-projection', from:['eco-genetic-criticality','eco-genetic-warning-extensions'], to:['egwee'], type:'empirical-projection', status:'bounded', condition:'自然系で測定・表現・残余文脈を吟味する。有限モデルや遺伝的警告の検証と同一視しない。'},
    {id:'state-payoff', from:['eco-genetic-warning-extensions'], to:['payoff'], type:'context-interface', status:'proposed', condition:'同一系で関係状態を先に測り、利得座標L(e), s(e), K(e)等への写像を示す。'},
    {id:'architecture-state', from:['payoff','bita'], to:['eco-genetic-warning-extensions'], type:'reverse-interface', status:'open', condition:'同一系・同一尺度で、構造の変更→相互作用構造→未来機能を測定・介入する。'},
    {id:'island-urban', from:['island','izu-core'], to:['egwee'], type:'natural-regime-test', status:'proposed', condition:'候補状態で独立な未来を予測した後、島・都市という起源や履歴の残余情報を検定する。'},
    {id:'mrm-mrod', from:['mrm'], to:['mrod'], type:'response-adapter', status:'open', condition:'MRMの応答署名・プローブ・費用を、MRODの許容集合と結果分割へ明示的に写す。'},
    {id:'ced-mrod', from:['ced'], to:['mrod'], type:'target-mechanism-adapter', status:'open', condition:'対象解像度と機構解像度を混同せず、同じ候補観測・リスク・費用の契約を作る。'},
    {id:'eog-mrod', from:['eog'], to:['mrod'], type:'world-observation-adapter', status:'open', condition:'残存世界の不一致を候補観測の分割へ写し、世界IDを因果的真実と言い換えずに縮約を確かめる。'},
    {id:'same-system', from:['mrod','rec','tnoa'], to:['pollipi','insepi'], type:'physical-validation', status:'open', condition:'同一物理系で独立な露出真値、凍結した較正、未見データの採点を揃える。'},
    {id:'natural-state', from:['crest','ced'], to:['egwee'], type:'required-state-test', status:'open', condition:'必要状態・観測契約・未見の未来の応答を同一自然系で同期する。'}
  ],
  rules: [
    '高さは読解の順序であって、理論の優劣・因果順序・実証の強さではない。',
    '世界→観測→報告は、一般には集合の包含ではなく写像と同値類。内外は写像や契約を指定して初めて言える。',
    '各リポは一つの入口を持つが、その仕事は複数の層をまたぐ。',
    '視点は可視性だけを変える。リポの位置・接続の向き・証拠の強さは変えない。',
    '見つけた接点と、科学的に閉合した接点は別。プレイで証拠の状態を昇格させない。',
    '最後の回収は、現地へ戻る問いの循環。全仮説の証明ではない。'
  ],
  sources: [
    {repo:'zuizui0223.github.io',path:'world-ontology-audit.json',blob:'2166993646f9525f543d2a475277e0bdb5e8b85b'},
    {repo:'zuizui0223.github.io',path:'puzzle-closure-audit.json',blob:'66994c67efa138986ff55f2ae87b586174c00cb4'},
    {repo:'zuizui0223.github.io',path:'repo-audit.json',blob:'08d494e09a73f90c6dd1dd025e498134b6f42023'},
    {repo:'crest',path:'README.md',blob:'16c8dfba6f6351a79cd61ebe4976539425df4788'},
    {repo:'mrod',path:'README.md',blob:'51a3ba48746b0d772da3e8d11dc41af2d5f2fbbb'},
    {repo:'payoff',path:'README.md',blob:'1b361d52062f539903a06070aa2faa629eae55a9'},
    {repo:'egwee',path:'README.md',blob:'1199292fe1d6984c6fbbd4928729f6edf880d688'},
    {repo:'acsp',path:'README.md',blob:'a56e8dd63958ec2a2354a6e7b0ed195d1582e83f'},
    {repo:'eog',path:'README.md',blob:'d271ae92af397efd21cabd1f5bb07d5c09ea9fa8'},
    {repo:'284b',path:'docs/product_b_eog_sdmr_relation_space_alignment.md',blob:'a5ca53b09aed0adaaebeff24602a58d833f7ac94'}
  ]
};
