"use strict";
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {test}=require('node:test');
function load(){const c={window:{}};for(const f of ['tower-data.js','portfolio-20260908.js','horizontal-data.js','portfolio-current.js','tower-architecture.js']){if(fs.existsSync(f))vm.runInNewContext(fs.readFileSync(f,'utf8'),c);}return c.window;}
test('all 40 research rooms and canonical renamed repositories are present',()=>{const w=load(), ids=w.ZUIZUI_TOWER.repos.map(r=>r[0]);assert.equal(ids.length,40);for(const id of ['slk','esdm','iwe','Structural','egc','egwe'])assert(ids.includes(id));assert(!ids.includes('eco-genetic-criticality'));});
test('syndrome routes are absent from rendered geometry, not hidden with CSS',()=>{const w=load(),m=w.ZUIZUI_ARCHITECTURE.build(w.ZUIZUI_TOWER);assert.equal(m.syndromeAssembly.renderedRoutes,false);assert(!m.syndromeAssembly.individual.route.length);assert(!m.syndromeAssembly.spatial.route.length);});
test('horizontal connections exist for every room, with source and relationship kind',()=>{const w=load(),d=w.ZUIZUI_TOWER;assert(d.horizontal);for(const r of d.repos)assert(d.horizontal.links.some(l=>l.from===r[0]||l.to===r[0]),r[0]);for(const l of d.horizontal.links){assert(l.kind&&l.note&&l.source);assert.equal(l.scientific_edge,false);}});
test('20 versioned interfaces retained; reading relations do not promote them',()=>{const w=load();assert.equal(w.ZUIZUI_TOWER.contacts.length,20);assert(w.ZUIZUI_TOWER.horizontal?.separateFromScientificContacts);});

test('audited reading ledger is identical to the loaded runtime source',()=>{const h=load().ZUIZUI_TOWER.horizontal;assert.deepEqual(JSON.parse(JSON.stringify(h)),JSON.parse(fs.readFileSync('horizontal-audit.json','utf8')));});
test('every reading relation has known endpoints and an inspected source',()=>{const d=load().ZUIZUI_TOWER,h=d.horizontal,ids=new Set(d.repos.map(r=>r[0]));for(const l of h.links){assert(ids.has(l.from)&&ids.has(l.to));assert(h.kinds[l.kind]);const s=h.sources[l.source];assert(s&&/^[a-f0-9]{40}$/.test(s.blob));assert(s.read_lines[0]>=1&&s.read_lines[1]>=s.read_lines[0]);assert(['documented','proposed'].includes(l.status));assert(l.ceiling);}assert(h.links.filter(l=>l.from==='esdm'||l.to==='esdm').every(l=>l.status==='proposed'));});
test('old architecture ownership has an explicit revision receipt',()=>{const d=load().ZUIZUI_TOWER,c=d.contacts.find(c=>c.id==='architecture-game');assert.deepEqual(Array.from(c.to),['slk']);assert(!c.from.includes('bita'));assert(d.contactRevisions.some(r=>r.id===c.id&&r.previous.from.includes('bita')));});
test('the removed exterior routes leave no layer-four syndrome geometry',()=>{const w=load(),m=w.ZUIZUI_ARCHITECTURE.build(w.ZUIZUI_TOWER);assert(!m.faces.some(f=>f.synthesis==='syndrome-assembly'&&f.layer===4));assert(m.resolutionFracture&&m.syndromeAssembly.endpoints.length===3);});
