'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context={window:{}};
vm.runInNewContext(fs.readFileSync('tower-data.js','utf8'),context);
vm.runInNewContext(fs.readFileSync('portfolio-20260908.js','utf8'),context);
vm.runInNewContext(fs.readFileSync('tower-echo-data.js','utf8'),context);
vm.runInNewContext(fs.readFileSync('tower-architecture.js','utf8'),context);
const d=JSON.parse(JSON.stringify(context.window.ZUIZUI_TOWER));
const echoes=JSON.parse(JSON.stringify(context.window.ZUIZUI_TOWER_ECHOES));
const ontology=JSON.parse(fs.readFileSync('tower-ontology-audit.json','utf8'));
const closure=JSON.parse(fs.readFileSync('tower-closure-audit.json','utf8'));
const syndromeAudit=JSON.parse(fs.readFileSync('syndrome-assembly-2026-09-09.json','utf8'));
assert.equal(ontology.schema,'zuizui.tower_ontology.v1');
assert.equal(ontology.inventory.owner_total,37);
assert.equal(ontology.inventory.research_programmes,36);
assert.deepEqual(ontology.inventory.staging_unclassified,[]);
assert.equal(ontology.floors.length,5);
assert(ontology.orthogonal_worlds.cross_estimand_relation_space.repositories.includes('284b'));
assert.equal(closure.schema,'zuizui.tower_closure.v1');
assert.equal(closure.visitor_state.scientific_effect,'none');
assert(closure.contacts.some(c=>c.id==='relation_space_to_cross_role_validation'&&c.status==='open'));
assert(closure.bounded_receipts.some(c=>c.id==='284b_layer1_feasibility'&&c.status==='bounded'));
assert.equal(syndromeAudit.schema,'zuizui.syndrome_assembly_synthesis.v1');
assert.equal(syndromeAudit.scientific_edge,false);
const ids=new Set(d.repos.map(r=>r[0]));
assert.equal(ids.size,d.repos.length);
assert.equal(d.repos.length,36);
assert.equal(d.floors.length,5);
assert.equal(d.motifs.length,5);
assert.equal(d.contacts.length,20);
const contacts=new Map(d.contacts.map(c=>[c.id,c]));
assert.equal(contacts.size,d.contacts.length);
for(const r of d.repos)assert(r[1]>=0&&r[1]<5);
for(const c of d.contacts){
  for(const id of [...c.from,...c.to])assert(ids.has(id),id);
  assert(['established','bounded','proposed','open'].includes(c.status));
  assert(c.condition.length>0);
}
for(const m of d.motifs){
  assert(m.source&&m.path&&/^[a-f0-9]{40}$/.test(m.sourceBlob));
  assert(m.receipt.length>0);
  for(const id of m.repos)assert(ids.has(id));
  for(const id of m.contacts)assert(contacts.has(id));
}
assert.deepEqual(new Set(d.motifs.flatMap(m=>m.contacts)),new Set(contacts.keys()));
const repoFloor=new Map(d.repos.map(r=>[r[0],r[1]])),motifs=new Set(d.motifs.map(m=>m.id));
assert.equal(echoes.length,5);
assert.equal(new Set(echoes.map(e=>e.id)).size,echoes.length);
for(const e of echoes){
  assert(ids.has(e.from)&&ids.has(e.to));
  assert.notEqual(repoFloor.get(e.from),repoFloor.get(e.to),'echoes must recur across floors');
  assert(motifs.has(e.unlock));
  const c=contacts.get(e.contact);assert(c,e.contact);
  assert(c.from.includes(e.from),`${e.id} source must already exist in typed contact`);
  assert(c.to.includes(e.to),`${e.id} target must already exist in typed contact`);
}
assert(d.repos.find(r=>r[0]==='284b')[4].includes('relation-check'));
assert.equal(d.repos.find(r=>r[0]==='TTF')[1],1);
assert.equal(d.repos.find(r=>r[0]==='adaptive-gain')[1],2);
assert.equal(d.syntheses.length,3);
assert(d.syntheses.every(s=>s.scientific_edge===false));
const resolution=d.syntheses.find(s=>s.id==='state-resolution');
assert.equal(resolution.visual.mode,'architectural-perspective');
assert.equal(resolution.visual.floor,3);
assert.deepEqual(resolution.visual.stages,[1,2,3]);
const syndrome=d.syntheses.find(s=>s.id==='syndrome-assembly');
assert(syndrome);
assert.equal(syndrome.visual.mode,'bifurcate-reconverge');
assert.equal(syndrome.visual.source,'payoff');
assert.deepEqual(syndrome.visual.spatial,['TTF']);
assert(syndrome.visual.individual.includes('shimahotarubukuro'));
assert.deepEqual(syndrome.visual.endpoints,['pollination-syndrome','selfing-syndrome','island-syndrome']);
const model=context.window.ZUIZUI_ARCHITECTURE.build(context.window.ZUIZUI_TOWER);
assert(model.resolutionFracture);
assert.equal(model.resolutionFracture.id,'state-resolution');
assert.equal(model.resolutionFracture.scientific_edge,false);
assert.equal(model.resolutionFracture.floor,3);
assert.equal(model.resolutionFracture.archiveCrack.length,5);
assert.equal(model.resolutionFracture.displacedPlanes.length,2);
assert.equal(model.resolutionFracture.completion.bars.length,2);
assert.equal(model.resolutionFracture.completion.slash.length,13);
assert(model.faces.some(f=>f.synthesis==='state-resolution'&&f.layer===1));
assert(model.faces.some(f=>f.synthesis==='state-resolution'&&f.layer===2));
assert(model.faces.some(f=>f.synthesis==='state-resolution'&&f.layer===3));
assert(model.faces.filter(f=>f.synthesis==='state-resolution').every(f=>f.role==='clue'));
assert(model.syndromeAssembly);
assert.equal(model.syndromeAssembly.scientific_edge,false);
assert.equal(model.syndromeAssembly.source,'payoff');
assert.equal(model.syndromeAssembly.spatial.repository,'TTF');
assert.equal(model.syndromeAssembly.endpoints.length,3);
assert(model.faces.some(f=>f.synthesis==='syndrome-assembly'&&f.layer===4));
assert(model.faces.some(f=>f.synthesis==='syndrome-assembly'&&f.layer===0));
assert(model.faces.filter(f=>f.synthesis==='syndrome-assembly').every(f=>f.role==='clue'));
assert(context.window.ZUIZUI_ARCHITECTURE.version.includes('resolution-perspective-1'));
assert(context.window.ZUIZUI_ARCHITECTURE.version.includes('syndrome-bifurcation-1'));
assert.equal(contacts.get('state-payoff').status,'proposed');
assert.equal(contacts.get('field-return').status,'open');
assert(!contacts.has('payoff-to-ttf'));
assert(!contacts.has('syndrome-assembly'));
assert(!fs.readFileSync('index.html','utf8').includes('src="world-game'));
console.log('Tower contract: 36 entrances, 5 motifs, 20 typed contacts; state-resolution and syndrome-assembly remain architectural non-edge syntheses.');
